### ISSUE TITLE
Script fails to complete with CX21 instances

### ISSUE THREAD

**Issue by rikharink** [hughobrien/k3os-hetzner#1]
I was trying to use your terraform scripts to setup a k3s cluster with instances of size CX21.
I changed the default_server_type in variables.tf and ran the script and everytime I did this I got the following error:  `mount: /run/k3os/iso: wrong fs type, bad option, bad superblock on /dev/sda, missing codepage or helper program, or other error.`

If I ran the script with CX11 as the default_server_type everything worked as expected. Any idea why this goes wrong with CX21 instances? I did also notice the following message during the execution of the script: `Failed to find /dev/sdap1 or /dev/sda1 to format.`

**Comment by hughobrien** [comment]
The second error is the trouble, first I believe is just k3OS script looking for a local ISO before giving up and downloading it.

I can replicate this so will poke around and get back to you shortly. Thanks for raising it.

**Comment by hughobrien** [comment]
Seems the partition table changes aren't synced. I've opened a PR for the upstream: https://github.com/rancher/k3os/pull/407

In the meantime I've adjusted this repo to pull the script from my fork, so you should just be able to `git pull` and try again.

**Comment by rikharink** [comment]
Thanks for the quick response, will try again later!

EDIT: Just tried it, also works on my end! Thanks again for the quick fix :+1:

**Comment by hughobrien** [comment]
No worries, they merged my PR also.

Have fun and thanks for flagging this.
