### ISSUE TITLE
How to create the correct secrets/k3s-cert.yaml

### ISSUE THREAD

**Issue by juwei80** [hughobrien/k3os-hetzner#2]
Hello! :)

First of all: your scripts are working very well, just needed to update some parts to be able to run it using windows.
Great work!

Can you please tell me how to backup the correct set of the letsencrypt certificates so that they work just after destroying and rebuilding the whole cluster?

I have tried it that way, but didn't work:
```
kubectl get -o yaml -n default secrets,certificates k3s-cert > secrets/k3s-cert.yaml
kubectl get -o yaml -n longhorn-system secrets,certificates longhorn-cert > secrets/longhorn-cert.yaml
kubectl get -o yaml -n docker-registry secrets,certificates registry-cert > secrets/registry-cert.yaml
kubectl get -o yaml -n prometheus secrets,certificates prometheus-cert > secrets/prometheus-cert.yaml
kubectl get -o yaml -n argo secrets,certificates argo-cert > secrets/argo-cert.yaml
kubectl get -o yaml -n argocd secrets,certificates argocd-cert > secrets/argocd-cert.yaml
```
After terraforming has been finished, the nginx just complains:

400 Bad Request
The SSL certificate error

What did i miss to backup?

Best regards,
Juergen

**Comment by hughobrien** [comment]
does the `./backup.sh` script work?

**Comment by juwei80** [comment]
Thank you for your quick reply!
OMG! I have actually not seen this script :( Umm...
Sorry for making an issue - i will test it out. This ticket can be closed :)

**Comment by hughobrien** [comment]
No worries :)

Glad to hear it's helping. Be aware though, I'm not 100% sure the lets encrypt auto-renew is working correctly out of the box. Keep an eye out for the reminder emails in a few months just in case.

**Comment by juwei80** [comment]
The backup script worked, looks like i have missed the ingress-cert.
