### ISSUE TITLE
Amazing project but too bad not using the CCM

### ISSUE THREAD

**Issue by mysticaltech** [hughobrien/k3os-hetzner#3]
Hello @hughobrien, thank you for that really nice project, however now that Hetzner has its own ccm over at https://github.com/hetznercloud/hcloud-cloud-controller-manager, it would be great to take advantage of it. 

As with it, we can use Hetzner's native private network without tunnel over something like cilium with native routing. Also, we can take advantage of the LoadBalancer that now works. 

Would you consider making those changes?

**Comment by hughobrien** [comment]
Yes that would definitely be a nice addition, I have no plans to work on this repo for some time however

**Comment by mysticaltech** [comment]
Awesome, for the future, a great example of how the official Hetzner team does it with k3s and cilium, in their e2e tests here https://github.com/hetznercloud/hcloud-cloud-controller-manager/tree/master/e2etests
